spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.security.user.name=${SPRING_SECURITY_DEV_USER:default_dev_user}
spring.security.user.password=${SPRING_SECURITY_DEV_PASSWORD:default_dev_password}

clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

server.servlet.context-path=/api/v1.0

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.defer-datasoeurce-initialization=true
spring.sql.init.mode=always

logging.level.org.springframework.security=TRACE
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
